require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNAppToPhone' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!
  pod 'NexmoClient'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  use_react_native!(:path => config["reactNativePath"])

  target 'RNAppToPhoneTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'RNAppToPhone-tvOS' do
  # Pods for RNAppToPhone-tvOS

  target 'RNAppToPhone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
